---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: local
service_endpoint_1: http://localhost:8080/product
  
---
spring:
  profiles: dev
service_endpoint_1: http://gapstrainingbff.mybluemix.net/product
