service_endpoint_1: http://9.45.127.235.mybluemix.net/product/1
environment: "production"
environment_description: "where successful master branch products come together in a harmonious way in a delightful release"